version: '3.5'

services:
    web:
        build: .
        image: web:latest
        container_name: happyparkingweb
        restart: always
        ports:
            - 80:80
        networks:
            - mynet

networks:
  mynet:
      name: mynet
      driver: bridge
