version: '3.5'

services:
    reverseproxy:
        build: .
        image: reverseproxy:latest
        ports:
            - 3000:3000
        restart: always
        networks:
            - mynet

networks:
  mynet:
      name: mynet
      driver: bridge
